In [462]:
import numpy as np
import pandas as pd
import random

In [463]:
dell_data=pd.read_csv("data/dell_data.csv")

In [464]:
dell_data.shape

(60, 13)

In [465]:
apple_data=pd.read_csv("data/apple_data.csv")

In [466]:
apple_data.shape

(20, 13)

In [467]:
laptop_data=pd.read_csv("data/laptop_data.csv")

In [468]:
#laptop_data=pd.read_csv("data/laptops.csv")

In [469]:
laptop_data.shape

(80, 13)

In [470]:
#laptop_data.to_csv("data/laptop_data.csv")

In [471]:
laptop_data.head()


Id Company        Product   TypeName  Inches  \
0  21    Dell         XPS 13  Ultrabook    13.3   
1  22    Dell  Latitude 5590  Ultrabook    15.6   
2  23    Dell  Inspiron 5370  Ultrabook    13.3   
3  24    Dell  Latitude 5590  Ultrabook    15.6   
4  25    Dell  Inspiron 7577     Gaming    15.6   

                            ScreenResolution                          Cpu  \
0  IPS Panel Full HD / Touchscreen 1920x1080   Intel Core i5 8250U 1.6GHz   
1                          Full HD 1920x1080   Intel Core i7 8650U 1.9GHz   
2                IPS Panel Full HD 1920x1080   Intel Core i7 8550U 1.8GHz   
3                IPS Panel Full HD 1920x1080   Intel Core i5 8250U 1.6GHz   
4                IPS Panel Full HD 1920x1080  Intel Core i7 7700HQ 2.8GHz   

    Ram                  Memory                         Gpu       OpSys  \
0   8GB               128GB SSD      Intel UHD Graphics 620  Windows 10   
1   8GB  256GB SSD +  256GB SSD      Intel UHD Graphics 620  Windows 10   
2   8GB               256GB SSD              AMD Radeon 530  Windows 10   
3   8GB               256GB SSD      Intel UHD Graphics 620  Windows 10   
4  16GB    128GB SSD +  1TB HDD  Nvidia GeForce GTX 1050 Ti  Windows 10   

   Weight  Price_euros  
0  1.22kg       979.00  
1  1.88kg      1298.00  
2   1.4kg       955.00  
3  1.88kg      1096.16  
4  2.65kg      1349.00

In [472]:
laptop_data['Weight'] = laptop_data['Weight'].map(lambda x: x.rstrip('kg'))
laptop_data['Ram'] = laptop_data['Ram'].map(lambda x: x.rstrip('GB'))

In [473]:
laptop_data=laptop_data.drop('ScreenResolution', axis=1)

In [474]:
laptop_data=laptop_data.drop('Weight', axis=1)

In [475]:
laptop_data.dtypes

Id               int64
Company         object
Product         object
TypeName        object
Inches         float64
Cpu             object
Ram             object
Memory          object
Gpu             object
OpSys           object
Price_euros    float64
dtype: object

In [476]:
laptop_data["Ram"] = pd.to_numeric(laptop_data["Ram"])

In [477]:
laptop_data.dtypes

Id               int64
Company         object
Product         object
TypeName        object
Inches         float64
Cpu             object
Ram              int64
Memory          object
Gpu             object
OpSys           object
Price_euros    float64
dtype: object

In [478]:
X=laptop_data.values

In [479]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()

In [480]:
laptop_data.head()

Id Company        Product   TypeName  Inches                          Cpu  \
0  21    Dell         XPS 13  Ultrabook    13.3   Intel Core i5 8250U 1.6GHz   
1  22    Dell  Latitude 5590  Ultrabook    15.6   Intel Core i7 8650U 1.9GHz   
2  23    Dell  Inspiron 5370  Ultrabook    13.3   Intel Core i7 8550U 1.8GHz   
3  24    Dell  Latitude 5590  Ultrabook    15.6   Intel Core i5 8250U 1.6GHz   
4  25    Dell  Inspiron 7577     Gaming    15.6  Intel Core i7 7700HQ 2.8GHz   

   Ram                  Memory                         Gpu       OpSys  \
0    8               128GB SSD      Intel UHD Graphics 620  Windows 10   
1    8  256GB SSD +  256GB SSD      Intel UHD Graphics 620  Windows 10   
2    8               256GB SSD              AMD Radeon 530  Windows 10   
3    8               256GB SSD      Intel UHD Graphics 620  Windows 10   
4   16    128GB SSD +  1TB HDD  Nvidia GeForce GTX 1050 Ti  Windows 10   

   Price_euros  
0       979.00  
1      1298.00  
2       955.00  
3      1096.16  
4      1349.00

In [481]:
X[:, 5] = labelencoder_X.fit_transform(X[:, 5])

In [482]:
X[:, 9]=labelencoder_X.fit_transform(X[:,9])

In [483]:

X[:, 7]=labelencoder_X.fit_transform(X[:,7])
X[:, 8]=labelencoder_X.fit_transform(X[:,8])

In [484]:
X

array([[21, 'Dell', 'XPS 13', 'Ultrabook', 13.3, 18, 8, 1, 16, 1, 979.0],
       [22, 'Dell', 'Latitude 5590', 'Ultrabook', 15.6, 30, 8, 7, 16, 1,
        1298.0],
       [23, 'Dell', 'Inspiron 5370', 'Ultrabook', 13.3, 29, 8, 5, 0, 1,
        955.0],
       [24, 'Dell', 'Latitude 5590', 'Ultrabook', 15.6, 18, 8, 5, 16, 1,
        1096.16],
       [25, 'Dell', 'Inspiron 7577', 'Gaming', 15.6, 27, 16, 2, 22, 1,
        1349.0],
       [26, 'Dell', 'XPS 13', 'Ultrabook', 13.3, 18, 8, 5, 16, 1, 1629.0],
       [27, 'Dell', 'Inspiron 7773', 'Notebook', 17.3, 29, 16, 12, 17, 1,
        1549.0],
       [28, 'Dell', 'XPS 15', 'Notebook', 15.6, 27, 16, 12, 21, 1,
        2397.0],
       [29, 'Dell', 'Inspiron 5770', 'Notebook', 17.3, 29, 8, 2, 0, 1,
        1085.0],
       [30, 'Dell', 'Inspiron 5370', 'Ultrabook', 13.3, 29, 8, 5, 0, 1,
        931.88],
       [31, 'Dell', 'Inspiron 5379', '2 in 1 Convertible', 13.3, 29, 16,
        12, 16, 1, 1279.0],
       [32, 'Dell', 'Alienware 17', 'Gami

In [485]:
from sklearn.cluster import KMeans

In [486]:
X_fit=X[:,4:11]
print(X_fit)

[[13.3 18 8 1 16 1 979.0]
 [15.6 30 8 7 16 1 1298.0]
 [13.3 29 8 5 0 1 955.0]
 [15.6 18 8 5 16 1 1096.16]
 [15.6 27 16 2 22 1 1349.0]
 [13.3 18 8 5 16 1 1629.0]
 [17.3 29 16 12 17 1 1549.0]
 [15.6 27 16 12 21 1 2397.0]
 [17.3 29 8 2 0 1 1085.0]
 [13.3 29 8 5 0 1 931.88]
 [13.3 29 16 12 16 1 1279.0]
 [17.3 27 16 6 23 1 2456.34]
 [13.3 29 16 3 16 1 2499.0]
 [15.6 29 8 8 0 1 1142.4]
 [15.6 31 8 13 26 1 1993.0]
 [15.6 23 16 5 26 1 1975.0]
 [15.6 29 8 2 0 1 979.0]
 [15.6 23 16 12 26 1 2338.0]
 [15.6 26 8 5 18 1 1369.0]
 [13.3 18 8 1 16 1 1599.0]
 [15.6 26 16 5 18 1 1537.39]
 [15.6 27 16 3 21 1 2399.0]
 [15.6 29 16 8 0 1 1135.0]
 [14.0 12 8 5 5 1 1229.0]
 [15.6 24 8 2 19 1 1207.0]
 [12.5 26 16 5 9 1 1859.0]
 [15.6 22 16 2 24 1 1099.0]
 [15.6 24 16 5 3 1 1181.27]
 [13.3 13 8 5 9 1 1499.0]
 [15.6 27 16 12 22 1 1679.0]
 [15.6 13 8 1 9 1 945.0]
 [12.5 26 8 5 9 1 1690.0]
 [15.6 15 8 10 9 1 935.0]
 [13.3 28 8 12 8 1 2013.1]
 [13.3 28 16 5 8 1 1649.0]
 [14.0 16 8 5 9 1 1205.0]
 [15.6 27 16 2 22 1 1

In [487]:
kmeans = KMeans(init='k-means++', n_clusters=8, n_init=100).fit(X[:,4:11])

In [488]:
classes=pd.DataFrame(kmeans.predict(X_fit))

In [489]:
laptop_data=pd.concat([laptop_data,classes],axis=1)

In [490]:
laptop_data.head()

Id Company        Product   TypeName  Inches                          Cpu  \
0  21    Dell         XPS 13  Ultrabook    13.3   Intel Core i5 8250U 1.6GHz   
1  22    Dell  Latitude 5590  Ultrabook    15.6   Intel Core i7 8650U 1.9GHz   
2  23    Dell  Inspiron 5370  Ultrabook    13.3   Intel Core i7 8550U 1.8GHz   
3  24    Dell  Latitude 5590  Ultrabook    15.6   Intel Core i5 8250U 1.6GHz   
4  25    Dell  Inspiron 7577     Gaming    15.6  Intel Core i7 7700HQ 2.8GHz   

   Ram                  Memory                         Gpu       OpSys  \
0    8               128GB SSD      Intel UHD Graphics 620  Windows 10   
1    8  256GB SSD +  256GB SSD      Intel UHD Graphics 620  Windows 10   
2    8               256GB SSD              AMD Radeon 530  Windows 10   
3    8               256GB SSD      Intel UHD Graphics 620  Windows 10   
4   16    128GB SSD +  1TB HDD  Nvidia GeForce GTX 1050 Ti  Windows 10   

   Price_euros  0  
0       979.00  3  
1      1298.00  0  
2       955.00  3  
3      1096.16  6  
4      1349.00  0

In [491]:
laptop_data.columns=[   'Id', 'Company',     'Product',    'TypeName',      'Inches',
               'Cpu',         'Ram',      'Memory',         'Gpu',
             'OpSys', 'Price_euros',             'Class']

In [509]:
laptop_data.to_csv("data/results.csv", index=False)

In [493]:
import pickle

In [494]:
pickle.dump(kmeans, open("model/kmeans.pkl", "wb"))

In [495]:
model=pickle.load(open("model/kmeans.pkl","rb"))

In [496]:
item_class=model.predict([[1,1,1,1,1,1,1301]]).tolist().pop()
print(item_class)

0


In [510]:
laptop_data.head()

Id Company        Product   TypeName  Inches                          Cpu  \
0  21    Dell         XPS 13  Ultrabook    13.3   Intel Core i5 8250U 1.6GHz   
1  22    Dell  Latitude 5590  Ultrabook    15.6   Intel Core i7 8650U 1.9GHz   
2  23    Dell  Inspiron 5370  Ultrabook    13.3   Intel Core i7 8550U 1.8GHz   
3  24    Dell  Latitude 5590  Ultrabook    15.6   Intel Core i5 8250U 1.6GHz   
4  25    Dell  Inspiron 7577     Gaming    15.6  Intel Core i7 7700HQ 2.8GHz   

   Ram                  Memory                         Gpu       OpSys  \
0    8               128GB SSD      Intel UHD Graphics 620  Windows 10   
1    8  256GB SSD +  256GB SSD      Intel UHD Graphics 620  Windows 10   
2    8               256GB SSD              AMD Radeon 530  Windows 10   
3    8               256GB SSD      Intel UHD Graphics 620  Windows 10   
4   16    128GB SSD +  1TB HDD  Nvidia GeForce GTX 1050 Ti  Windows 10   

   Price_euros  Class  
0       979.00      3  
1      1298.00      0  
2       955.00      3  
3      1096.16      6  
4      1349.00      0

In [498]:
laptop_data.shape

(80, 12)

In [524]:
result_data=laptop_data.loc[laptop_data['Class'] == item_class]
result_data=result_data.loc[laptop_data['Company']=="Dell" ]
result_data['Id'][0:3].tolist()

[22, 25, 31]

In [525]:
result_data[0:3]

Id Company        Product            TypeName  Inches  \
1   22    Dell  Latitude 5590           Ultrabook    15.6   
4   25    Dell  Inspiron 7577              Gaming    15.6   
10  31    Dell  Inspiron 5379  2 in 1 Convertible    13.3   

                            Cpu  Ram                  Memory  \
1    Intel Core i7 8650U 1.9GHz    8  256GB SSD +  256GB SSD   
4   Intel Core i7 7700HQ 2.8GHz   16    128GB SSD +  1TB HDD   
10   Intel Core i7 8550U 1.8GHz   16               512GB SSD   

                           Gpu       OpSys  Price_euros  Class  
1       Intel UHD Graphics 620  Windows 10       1298.0      0  
4   Nvidia GeForce GTX 1050 Ti  Windows 10       1349.0      0  
10      Intel UHD Graphics 620  Windows 10       1279.0      0